### ISSUE TITLE
[BUG] Startup Crashes with Optifine on Linux

### ISSUE THREAD

**Issue by hypherionmc** [hypherionmc/simple-rpc-public#14]
Confirmed an issue with Optifine on Linux systems, where the mod crashed at startup when installed with Optifine.

This can be replicated by starting a new 1.16.5 instance with optifine installed. It will crash. Run it again, and it will crash again. Run it again after that, and it works fine.

Tested on windows and the mod works as expected, so this is a linux related issue.

Cause seems to be the mod trying to load the config file faster than it writes it

**Comment by RaeTheGit** [comment]
Yes, indeed, I just came here to give an update that now it miraculously works together with OF. But, uh, yes. it's the third startup together with OF, as you said.

**Comment by hypherionmc** [comment]
As far as I can tell, it seems the mod creates the config file and tries to load it, but then the file appears to be corrupt. The second time, it will load it, but doesn't seem to load fully. And then the third time, it loads fine as if magic

**Comment by hypherionmc** [comment]
Hey @RaeTheGit, would you mind testing this build to confirm if it fixes the issue? I tested it on my side and it now loads fine with Optifine.

https://ci.explodingcreeper.me/job/Simple%20RPC/job/Forge/job/1.16/18/artifact/build/libs/simple-rpc-1.16.5-dev-18-all.jar

**Comment by hypherionmc** [comment]
Issue has been fixed in 2.3

**Comment by embeddedt** [comment]
I got the following crash after adding OptiFine to Valhesia 3, which contains Simple RPC 2.3.1. I use Ubuntu 18.04. Is this related?

```
[02Sep2021 19:39:27.125] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [mcwtrpdoors] Starting version check at https://raw.githubusercontent.com/sketchmacaw/macawsmods/master/trapdoors.jso
n
[02Sep2021 19:39:27.127] [Worker-Main-5/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: null
        Index: 1
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$2892/709360477@282230e1
java.lang.NullPointerException
        at me.hypherionmc.simplerpc.discordutils.RPCEvents.<init>(RPCEvents.java:47)
        at me.hypherionmc.simplerpc.ClientEventHandler.commonSetup(ClientEventHandler.java:42)
        at me.hypherionmc.simplerpc.SimpleRPC.lambda$null$3(SimpleRPC.java:37)
        at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:174)
        at me.hypherionmc.simplerpc.SimpleRPC.commonSetup(SimpleRPC.java:34)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)

[02Sep2021 19:39:27.129] [Worker-Main-5/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid simple-rpc
java.lang.NullPointerException: null
        at me.hypherionmc.simplerpc.discordutils.RPCEvents.<init>(RPCEvents.java:47) ~[simple-rpc:2.3.1]
        at me.hypherionmc.simplerpc.ClientEventHandler.commonSetup(ClientEventHandler.java:42) ~[simple-rpc:2.3.1]
        at me.hypherionmc.simplerpc.SimpleRPC.lambda$null$3(SimpleRPC.java:37) ~[simple-rpc:2.3.1]
        at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:174) ~[forge:?]
        at me.hypherionmc.simplerpc.SimpleRPC.commonSetup(SimpleRPC.java:34) ~[simple-rpc:2.3.1]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.2]
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_281]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_281]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_281]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) [?:1.8.0_281]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) [?:1.8.0_281]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) [?:1.8.0_281]
```

**Comment by hypherionmc** [comment]
Seems related... Ugrh. Does the game start after a couple of times as above or does it keep crashing?
