### ISSUE TITLE
[BUG] mouseClicked event handler

### ISSUE THREAD

**Issue by DIDIRUS4** [hypherionmc/simple-rpc-public#15]
After kick from server can't back in main menu
=================================

Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_634.method_2880()" because the return value of "net.minecraft.class_310.method_1562()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.35)
	at me.hypherionmc.simplerpc.Utils.parseVars(Utils.java:52)
	at me.hypherionmc.simplerpc.configuration.confighelpers.ServerListSection.getPresence(ServerListSection.java:51)
	at me.hypherionmc.simplerpc.discordutils.RPCEvents.doRPCStuff(RPCEvents.java:142)
	at me.hypherionmc.simplerpc.discordutils.RPCEvents.serverListRPC(RPCEvents.java:105)
	at net.minecraft.client.MinecraftClient.handler$bba000$init(MinecraftClient:8068)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient)
	at net.minecraft.client.gui.screen.DisconnectedScreen.method_19814(DisconnectedScreen:30)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:190)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1140)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by hypherionmc** [comment]
From the lack of information, I am guessing this is forge 1.17.1. If so, then I cannot replicate this issue. Mod works as expected, so this is either a conflict, or Not Enough crashes once again falsely blaming a mod

**Comment by DIDIRUS4** [comment]
It's Fabric 1.17.1. I'll test it without Not Enough Crashes

**Comment by DIDIRUS4** [comment]
![image](https://user-images.githubusercontent.com/77334306/128703538-81d020b4-d740-4a25-a45f-c053debb80d2.png)
[crash-2021-08-09_15.06.08-client.txt](https://github.com/hypherionmc/simple-rpc-public/files/6954370/crash-2021-08-09_15.06.08-client.txt)

**Comment by hypherionmc** [comment]
Okay this has to be a mod conflict. I tested on a clean install with just simple rpc and it works as expected, so something is interfering. Especially since the crash happens from a button click. 

Simple RPC has nothing to do with button clicks, besides its own "Discord Presence" button. Other than that, the mod doesn't care about buttons

**Comment by DIDIRUS4** [comment]
Okay, I'll trying found trouble mod
I'll write you as soon as I find :)

**Comment by ModifiedMC** [comment]
Please keep us posted! I also have this issue with a PointerException causing a crash on server join. I reverted to 2.2.1 & no issues so it must just be a compat issue with the latest RPC.

I'm running a pack with 230+ mods so a compat issue is def a possibility however the last version is stable

Heres my most recent crash report:
[crash-2021-08-09_13.43.03-client.txt](https://github.com/hypherionmc/simple-rpc-public/files/6956524/crash-2021-08-09_13.43.03-client.txt)

Forge Version 36.2.2

**Comment by hypherionmc** [comment]
Huh. Okay not cool. I check the code as well and I have no clue why that is an issue. I'll add some extra safe failing for it and release a hotfix asap

**Comment by hypherionmc** [comment]
@DIDIRUS4 @ModifiedMC Would you please mind trying this one and letting me know asap so I can push out the fix: https://ci.explodingcreeper.me/job/Simple%20RPC/job/Forge/job/1.16/19/artifact/build/libs/simple-rpc-1.16.5-dev-19-all.jar

**Comment by hypherionmc** [comment]
I hope this is fixed now
