### ISSUE TITLE
[BUG] Main Menu event doesn't work with KubeJS UI

### ISSUE THREAD

**Issue by frank89722** [hypherionmc/simple-rpc-public#16]
**Describe the bug**
Main Menu event never triggered when KubeJS UI installed

**To Reproduce**
1. Install with KubeJS UI

**Expected behavior**
Should show I'm in the main menu in discord but it doesn't.

**Screenshots**

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: windows 10
 - JAVA Version: 15
 - Mod Version: [HOTFIX] Simple RPC Forge 1.16.x 2.3.1
 - Discord Version: Stable 94294 (1ae620c)
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.2

**Additional context**

**Comment by hypherionmc** [comment]
Okay so KubeJS UI replaces the main menu with their own GUI, which would explain why it doesn't trigger. I'll add in support for this

**Comment by hypherionmc** [comment]
Would you mind please testing this build to see if it works for you? https://ci.hypherionmc.me/job/Simple%20RPC/job/Forge/job/1.16/21/artifact/build/libs/simple-rpc-1.16.5-dev-21.jar

**Comment by frank89722** [comment]
Wow you're really fast :O
Yes, it works now.

**Comment by frank89722** [comment]
Just found out an issue with this build.
Client stuck on joining word

Here is the log:
```[23Aug2021 22:57:32.496] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 3
	Listeners:
		0: HIGH
		1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplClient event(Lnet/minecraftforge/client/event/GuiOpenEvent;)V
		2: NORMAL
		3: ASM: me.hypherionmc.simplerpc.ClientEventHandler@5baea328 guiEvent(Lnet/minecraftforge/client/event/GuiOpenEvent;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda$2815/908435478@59eff566
java.lang.NullPointerException
	at me.hypherionmc.simplerpc.ClientEventHandler.guiEvent(ClientEventHandler.java:57)
	at net.minecraftforge.eventbus.ASMEventHandler_134_ClientEventHandler_guiEvent_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:837)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_184330_a(ClientPlayNetHandler.java:708)
	at net.minecraft.network.play.server.SPlayerPositionLookPacket.func_148833_a(SourceFile:56)
	at net.minecraft.network.play.server.SPlayerPositionLookPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

[23Aug2021 22:57:32.498] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.NullPointerException: null
	at me.hypherionmc.simplerpc.ClientEventHandler.guiEvent(ClientEventHandler.java:57) ~[simple-rpc:dev-21]
	at net.minecraftforge.eventbus.ASMEventHandler_134_ClientEventHandler_guiEvent_GuiOpenEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:837) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_184330_a(ClientPlayNetHandler.java:708) ~[?:?]
	at net.minecraft.network.play.server.SPlayerPositionLookPacket.func_148833_a(SourceFile:56) ~[?:?]
	at net.minecraft.network.play.server.SPlayerPositionLookPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.4-launcher.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by hypherionmc** [comment]
Whoops, my bad. This should fix both: https://ci.explodingcreeper.me/job/Simple%20RPC/job/Forge/job/1.16/22/artifact/build/libs/simple-rpc-1.16.5-dev-22.jar

**Comment by frank89722** [comment]
Umm, I got same error in build 22

**Comment by hypherionmc** [comment]
Urgh lol.... Okay I tested this one and it ran fine: https://ci.explodingcreeper.me/job/Simple%20RPC/job/Forge/job/1.16/23/artifact/build/libs/simple-rpc-1.16.5-dev-23.jar

**Comment by frank89722** [comment]
Okay build 23 is work. Thank's you C:

**Comment by hypherionmc** [comment]
Awesome. I'll release it later this week on Curse

**Comment by hypherionmc** [comment]
The release including this compat has been released. Sorry it took so long
