### ISSUE TITLE
[BUG] Crash at start (Maybe related to/the same as #3)

### ISSUE THREAD

**Issue by JoeJoeTV** [hypherionmc/simple-rpc-public#4]
**Describe the bug**
The game crashes at the Initialization stage.

**To Reproduce**
1. Launch the game with the mod installed.
2. Game crashes.

**Expected behavior**
The game should start normally.

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Linux Mint 20 Cinnamon 64 bit
 - JAVA Version: 11.0.9 (AdoptOpenJDK OpenJ9)
 - Mod Version: 1.4
 - Discord Version: Stable 73230 (a3191cd) Host 0.0.13
 - Minecraft Version: 1.16.4
 - ~~Forge~~ Fabric Version: 0.10.8

**Additional context**
[crash-2020-12-12_00.18.22-client.txt](https://github.com/hypherionmc/simple-rpc-public/files/5682024/crash-2020-12-12_00.18.22-client.txt)

**Comment by hypherionmc** [comment]
Hi there thanks for reporting. Okay from the log it appears to be the main library crashing, which can be because of two things:

1) Another linux bug in the socket library
2) Incompatibility with Java 11 (The mod is intended to be used with Java 8).
And a bonus one, just bad testing on my part for 1.16.4. 

Would it be possible for you to try running the mod on a 1.16.3 instance to see if the issue still occurs? 

As for java compatibility, most of the libs used by the mod is compiled for java 8 only, while some support java 11, so it's quite possible that, that is also an issue

**Comment by JoeJoeTV** [comment]
I used the 1.3 version of this mod in a client modpack with 1.16.3 and Java 11 and it worked fine.
I'm gonna try it with 1.4 on 1.16.3 now.

**Comment by JoeJoeTV** [comment]
I could also switch to Java 8 if really necessary,

**Comment by JoeJoeTV** [comment]
I tested running 1.4 with Minecraft 1.16.3 and Java 8(OpenJDK Hotspot) and it crashed with the same error: 
```Could not execute entrypoint stage 'client' due to errors, provided by 'simple-rpc'!```

Using Not Enough Crashes, which deobfuscates stacktraces, I got:
```java
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2020-12-12 17:34:09 CET
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'simple-rpc'!
    at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$zzh000$stopFabricInit(MinecraftClient:3360)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:437)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException
    at me.hypherionmc.simplerpc.client.SimpleRpcClient.onInitializeClient(SimpleRpcClient.java:23)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 19 more```

**Comment by hypherionmc** [comment]
Thank you for the information. Seems I screwed up the 1.16.4 build. I'll check it out and do a fix for it

**Comment by hypherionmc** [comment]
Hey @JoeJoeTV. Would you mind giving this build a shot to see if it fixes the issue please? https://ci.hypherionmc.me/job/Simple%20RPC/job/1.16.3%20(Fabric)/15/artifact/build/libs/simple-rpc-1.16.3-1.4.1.15.jar

**Comment by hypherionmc** [comment]
Above mentioned build didn't work, but a fix has been made and has been released. Please update to 1.4.1. If you still have this problem, please leave a comment

**Comment by JoeJoeTV** [comment]
Hello, sorry I didn't respond, I saw the reply too late, I tried the new 1.4.1 version and it starts, but now, the Rich Presence won't show up at all in Discord.
I also tried enabling "debugging" in the config to get more info, but I couldn't find anything in the log. 
I also tried using an empty config file, which crashed at start, so I deleted the config file, so it could generate a new one and it still didn't work.

Sidenote: How does the Hot reload feature added in 1.4 work?

**Comment by hypherionmc** [comment]
Could you maybe provide me with your latest.log after running the game once with the new version. Please also try running an instance with just simple-rpc installed. I made sure it was working before I released it, so it's weird that it doesn't now.

As for the hot reload, when you edit and save a config file, the changes show up almost instantly on your status (with the exception of the client ID. For that you still need to restart)

**Comment by hypherionmc** [comment]
I just re-tested with the 1.4.1 release and the status is showing up. This is very weird indeed

**Comment by JoeJoeTV** [comment]
I just tried it with only fabric-api and simple-rpc installed and it still didn't show up. I also let it generate a new empty config for the test.
Here is the log file: [latest.log](https://github.com/hypherionmc/simple-rpc-public/files/5719415/latest.log)

Versions:
- Fabric Loader: 0.10.8
- Fabric API: 0.28.3
- Simple RPC: 1.4.1
- Java Version: 1.8.0_275

**Comment by JoeJoeTV** [comment]
Update: I realized, that now, the old version also doesn't work anymore in my 1.16.4 instance and I also setup a fresh one with just mc 1.16.4, fabric loader 0.10.8, fabric api 0.27.1 and simple rpc 1.4.1, which also didn't work.
My old 1.16.3 instance still works and the 1.6.4 instance also HAD worked with 1.3. Maybe it has something to do with the newer fabric api.

**Comment by hypherionmc** [comment]
Okay this is really weird. I can see from your log that the mod isn't even trying to connect to discord, yet nothing on the discord side of the mod changed between 1.3 and 1.4. They still use the same libraries and code. It's just the config system that changed.

Sigh, I hate it when you get weird errors like this. DM me on discord so we can figure something out: hypherionsa#2361

**Comment by JoeJoeTV** [comment]
You don't accept friend requests and I don't think I am on a server where you are.

**Comment by hypherionmc** [comment]
You should be able to add me now
