### ISSUE TITLE
[BUG] Invalid predicate: >=1.1.x

### ISSUE THREAD

**Issue by TheKrafter** [hypherionmc/simple-rpc-public#79]
**Describe the bug**

When launching instance, fails during resolving mod compatibility because version uses a wildcard, but also uses comparison operator

Logs:
<details>

```diff
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:197)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:147)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:147)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	... 6 more
! Caused by: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at /home/krafter/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Krafter 1.20.4/.minecraft/mods/SimpleRPC-Fabric-1.20.4-3.2.5.jar: net.fabricmc.loader.api.VersionParsingException: Invalid predicate: >=1.1.x, version ranges with wildcards (.X) require using the equality operator or no operator at all!
	at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.readDependenciesContainer(V1ModMetadataParser.java:471)
	at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.parse(V1ModMetadataParser.java:151)
	at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:141)
	at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:104)
	at net.fabricmc.loader.impl.metadata.ModMetadataParser.parseMetadata(ModMetadataParser.java:44)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.parseMetadata(ModDiscoverer.java:494)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:316)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:278)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: net.fabricmc.loader.api.VersionParsingException: Invalid predicate: >=1.1.x, version ranges with wildcards (.X) require using the equality operator or no operator at all!
	at net.fabricmc.loader.impl.util.version.VersionPredicateParser.parse(VersionPredicateParser.java:65)
	at net.fabricmc.loader.impl.util.version.VersionPredicateParser.parse(VersionPredicateParser.java:105)
	at net.fabricmc.loader.api.metadata.version.VersionPredicate.parse(VersionPredicate.java:51)
	at net.fabricmc.loader.impl.metadata.ModDependencyImpl.<init>(ModDependencyImpl.java:39)
	at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.readDependenciesContainer(V1ModMetadataParser.java:469)
	... 14 more
```

</details>

**To Reproduce**
1. Install SimpleRPC
2. Launch Minecraft 1.20.4
3. Checking Mod set compatibility fails

**Expected behavior**

Game launches and is useable as normal.

**Screenshots**

![Incompatible Mod Set window from Fabric 0.15.3, showing a ParseMetadataException](https://github.com/hypherionmc/simple-rpc-public/assets/75903664/5fc7cf0c-b543-4875-b638-e0d5542b763e)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Linux x86_64 (Flatpak runtime)
 - JAVA Version: 17
 - Mod Version: 3.2.5
 - Discord Version: Stable 256231 (96a39c5)
 - Minecraft Version: 1.20.4
 - Forge/Fabric Version: Fabric 0.15.3

**Additional context**

**Comment by hypherionmc** [comment]
Oh for pete sake. Will push a hotfix shortly

**Comment by hypherionmc** [comment]
Fix has been pushed. Already live on Modrinth, might take a while for curse. They are a bit slow today.

Thanks for the report :)
